/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.points.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSvgPointsScopeProvider extends DelegatingScopeProvider {
}
