/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.coordinate.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.svg.coordinate.parser.antlr.internal.InternalSvgCoordinateParser;
import org.xtext.svg.coordinate.services.SvgCoordinateGrammarAccess;

public class SvgCoordinateParser extends AbstractAntlrParser {

	@Inject
	private SvgCoordinateGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSvgCoordinateParser createParser(XtextTokenStream stream) {
		return new InternalSvgCoordinateParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Coordinate";
	}

	public SvgCoordinateGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SvgCoordinateGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
