/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.preserveaspectratio.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.svg.preserveaspectratio.parser.antlr.internal.InternalSvgPreserveAspectRatioParser;
import org.xtext.svg.preserveaspectratio.services.SvgPreserveAspectRatioGrammarAccess;

public class SvgPreserveAspectRatioParser extends AbstractAntlrParser {

	@Inject
	private SvgPreserveAspectRatioGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSvgPreserveAspectRatioParser createParser(XtextTokenStream stream) {
		return new InternalSvgPreserveAspectRatioParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "PreserveAspectRatio";
	}

	public SvgPreserveAspectRatioGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SvgPreserveAspectRatioGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
