/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.viewbox;

import org.xtext.svg.viewbox.AbstractSvgViewboxRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SvgViewboxRuntimeModule extends AbstractSvgViewboxRuntimeModule {
}
