/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.localiri.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSvgLocalIriScopeProvider extends DelegatingScopeProvider {
}
