/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.viewbox.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSvgViewboxScopeProvider extends DelegatingScopeProvider {
}
