/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.transform;

import org.xtext.svg.transform.SvgTransformStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SvgTransformStandaloneSetup extends SvgTransformStandaloneSetupGenerated {
  public static void doSetup() {
    new SvgTransformStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
