/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.transform;

import org.xtext.svg.transform.AbstractSvgTransformRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SvgTransformRuntimeModule extends AbstractSvgTransformRuntimeModule {
}
