/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.lengths.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SvgLengthsAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/svg/lengths/parser/antlr/internal/InternalSvgLengths.tokens");
	}
}
