/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.href;

import org.xtext.svg.href.SvgHrefStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SvgHrefStandaloneSetup extends SvgHrefStandaloneSetupGenerated {
  public static void doSetup() {
    new SvgHrefStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
