/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.href;

import org.xtext.svg.href.AbstractSvgHrefRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SvgHrefRuntimeModule extends AbstractSvgHrefRuntimeModule {
}
