/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.preserveaspectratio.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSvgPreserveAspectRatioScopeProvider extends DelegatingScopeProvider {
}
