/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.localiri.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.svg.localiri.parser.antlr.internal.InternalSvgLocalIriParser;
import org.xtext.svg.localiri.services.SvgLocalIriGrammarAccess;

public class SvgLocalIriParser extends AbstractAntlrParser {

	@Inject
	private SvgLocalIriGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSvgLocalIriParser createParser(XtextTokenStream stream) {
		return new InternalSvgLocalIriParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "LocalIri";
	}

	public SvgLocalIriGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SvgLocalIriGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
