/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.transform.scoping;

import org.xtext.svg.transform.scoping.AbstractSvgTransformScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SvgTransformScopeProvider extends AbstractSvgTransformScopeProvider {
}
