/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.lengths


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SvgLengthsStandaloneSetup extends SvgLengthsStandaloneSetupGenerated {

	def static void doSetup() {
		new SvgLengthsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
