/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.preserveaspectratio;

import org.xtext.svg.preserveaspectratio.AbstractSvgPreserveAspectRatioRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SvgPreserveAspectRatioRuntimeModule extends AbstractSvgPreserveAspectRatioRuntimeModule {
}
