/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.preserveaspectratio;

import org.xtext.svg.preserveaspectratio.SvgPreserveAspectRatioStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SvgPreserveAspectRatioStandaloneSetup extends SvgPreserveAspectRatioStandaloneSetupGenerated {
  public static void doSetup() {
    new SvgPreserveAspectRatioStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
