/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.coordinate.formatting2;

import com.google.inject.Inject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.svg.coordinate.services.SvgCoordinateGrammarAccess;

@SuppressWarnings("all")
public class SvgCoordinateFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private SvgCoordinateGrammarAccess _svgCoordinateGrammarAccess;
  
  @Override
  public void format(final Object obj, final IFormattableDocument document) {
  }
}
