/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.href.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.svg.href.parser.antlr.internal.InternalSvgHrefParser;
import org.xtext.svg.href.services.SvgHrefGrammarAccess;

public class SvgHrefParser extends AbstractAntlrParser {

	@Inject
	private SvgHrefGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSvgHrefParser createParser(XtextTokenStream stream) {
		return new InternalSvgHrefParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Href";
	}

	public SvgHrefGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SvgHrefGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
