/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.length.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSvgLengthScopeProvider extends DelegatingScopeProvider {
}
