/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.path


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SvgPathStandaloneSetup extends SvgPathStandaloneSetupGenerated {

	def static void doSetup() {
		new SvgPathStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
