/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.href.formatting2;

import com.google.inject.Inject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.svg.href.services.SvgHrefGrammarAccess;

@SuppressWarnings("all")
public class SvgHrefFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private SvgHrefGrammarAccess _svgHrefGrammarAccess;
  
  @Override
  public void format(final Object obj, final IFormattableDocument document) {
  }
}
