/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.points.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.svg.points.services.SvgPointsGrammarAccess;

@SuppressWarnings("all")
public class SvgPointsSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SvgPointsGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Point_CommaKeyword_1_q;
	protected AbstractElementAlias match_Polygon_CommaKeyword_1_0_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SvgPointsGrammarAccess) access;
		match_Point_CommaKeyword_1_q = new TokenAlias(false, true, grammarAccess.getPointAccess().getCommaKeyword_1());
		match_Polygon_CommaKeyword_1_0_q = new TokenAlias(false, true, grammarAccess.getPolygonAccess().getCommaKeyword_1_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Point_CommaKeyword_1_q.equals(syntax))
				emit_Point_CommaKeyword_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Polygon_CommaKeyword_1_0_q.equals(syntax))
				emit_Polygon_CommaKeyword_1_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     x=Coordinate (ambiguity) y=Coordinate
	 */
	protected void emit_Point_CommaKeyword_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     points+=Point (ambiguity) points+=Point
	 */
	protected void emit_Polygon_CommaKeyword_1_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
