/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.viewbox.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.svg.viewbox.parser.antlr.internal.InternalSvgViewboxParser;
import org.xtext.svg.viewbox.services.SvgViewboxGrammarAccess;

public class SvgViewboxParser extends AbstractAntlrParser {

	@Inject
	private SvgViewboxGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSvgViewboxParser createParser(XtextTokenStream stream) {
		return new InternalSvgViewboxParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ViewBox";
	}

	public SvgViewboxGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SvgViewboxGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
