/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.viewbox.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SvgViewboxAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/svg/viewbox/parser/antlr/internal/InternalSvgViewbox.tokens");
	}
}
