/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.points.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.svg.points.parser.antlr.internal.InternalSvgPointsParser;
import org.xtext.svg.points.services.SvgPointsGrammarAccess;

public class SvgPointsParser extends AbstractAntlrParser {

	@Inject
	private SvgPointsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSvgPointsParser createParser(XtextTokenStream stream) {
		return new InternalSvgPointsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Polygon";
	}

	public SvgPointsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SvgPointsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
