/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.localiri.formatting2

import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.xtext.svg.localiri.services.SvgLocalIriGrammarAccess
import org.eclipse.xtext.formatting2.IFormattableDocument

class SvgLocalIriFormatter extends AbstractFormatter2 {
	
	@Inject extension SvgLocalIriGrammarAccess
	
	// TODO: implement for 
	override format(Object obj, IFormattableDocument document) {
		
	}
	
}
