/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.paint.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.svg.paint.parser.antlr.internal.InternalSvgPaintParser;
import org.xtext.svg.paint.services.SvgPaintGrammarAccess;

public class SvgPaintParser extends AbstractAntlrParser {

	@Inject
	private SvgPaintGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSvgPaintParser createParser(XtextTokenStream stream) {
		return new InternalSvgPaintParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Paint";
	}

	public SvgPaintGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SvgPaintGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
