/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.lengths.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSvgLengthsScopeProvider extends DelegatingScopeProvider {
}
