/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.path.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class SvgPathScopeProvider extends AbstractSvgPathScopeProvider {

}
