/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.transform.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SvgTransformAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/svg/transform/parser/antlr/internal/InternalSvgTransform.tokens");
	}
}
