/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.transform.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.svg.transform.parser.antlr.internal.InternalSvgTransformParser;
import org.xtext.svg.transform.services.SvgTransformGrammarAccess;

public class SvgTransformParser extends AbstractAntlrParser {

	@Inject
	private SvgTransformGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSvgTransformParser createParser(XtextTokenStream stream) {
		return new InternalSvgTransformParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Transform";
	}

	public SvgTransformGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SvgTransformGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
