/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.preserveaspectratio.validation;

import org.xtext.svg.preserveaspectratio.validation.AbstractSvgPreserveAspectRatioValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SvgPreserveAspectRatioValidator extends AbstractSvgPreserveAspectRatioValidator {
}
