/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.coordinate


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SvgCoordinateStandaloneSetup extends SvgCoordinateStandaloneSetupGenerated {

	def static void doSetup() {
		new SvgCoordinateStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
