/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.transform.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSvgTransformScopeProvider extends DelegatingScopeProvider {
}
