/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.viewbox.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.svg.viewbox.services.SvgViewboxGrammarAccess;

@SuppressWarnings("all")
public class SvgViewboxSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SvgViewboxGrammarAccess grammarAccess;
	protected AbstractElementAlias match_ViewBox_CommaKeyword_1_q;
	protected AbstractElementAlias match_ViewBox_CommaKeyword_3_q;
	protected AbstractElementAlias match_ViewBox_CommaKeyword_5_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SvgViewboxGrammarAccess) access;
		match_ViewBox_CommaKeyword_1_q = new TokenAlias(false, true, grammarAccess.getViewBoxAccess().getCommaKeyword_1());
		match_ViewBox_CommaKeyword_3_q = new TokenAlias(false, true, grammarAccess.getViewBoxAccess().getCommaKeyword_3());
		match_ViewBox_CommaKeyword_5_q = new TokenAlias(false, true, grammarAccess.getViewBoxAccess().getCommaKeyword_5());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_ViewBox_CommaKeyword_1_q.equals(syntax))
				emit_ViewBox_CommaKeyword_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ViewBox_CommaKeyword_3_q.equals(syntax))
				emit_ViewBox_CommaKeyword_3_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ViewBox_CommaKeyword_5_q.equals(syntax))
				emit_ViewBox_CommaKeyword_5_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     minX=Coordinate (ambiguity) minY=Coordinate
	 */
	protected void emit_ViewBox_CommaKeyword_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     minY=Coordinate (ambiguity) width=Length
	 */
	protected void emit_ViewBox_CommaKeyword_3_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     width=Length (ambiguity) height=Length
	 */
	protected void emit_ViewBox_CommaKeyword_5_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
