/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.length.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.svg.length.parser.antlr.internal.InternalSvgLengthParser;
import org.xtext.svg.length.services.SvgLengthGrammarAccess;

public class SvgLengthParser extends AbstractAntlrParser {

	@Inject
	private SvgLengthGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSvgLengthParser createParser(XtextTokenStream stream) {
		return new InternalSvgLengthParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Length";
	}

	public SvgLengthGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SvgLengthGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
