/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.length;

import org.xtext.svg.length.SvgLengthStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SvgLengthStandaloneSetup extends SvgLengthStandaloneSetupGenerated {
  public static void doSetup() {
    new SvgLengthStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
