/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.length;

import org.xtext.svg.length.AbstractSvgLengthRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SvgLengthRuntimeModule extends AbstractSvgLengthRuntimeModule {
}
