/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.points


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SvgPointsStandaloneSetup extends SvgPointsStandaloneSetupGenerated {

	def static void doSetup() {
		new SvgPointsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
