/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.paint.validation;

import org.xtext.svg.paint.validation.AbstractSvgPaintValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SvgPaintValidator extends AbstractSvgPaintValidator {
}
