/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.transform


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SvgTransformStandaloneSetup extends SvgTransformStandaloneSetupGenerated {

	def static void doSetup() {
		new SvgTransformStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
