/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.transform


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SvgTransformRuntimeModule extends AbstractSvgTransformRuntimeModule {
}
