/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.coordinate;

import org.xtext.svg.coordinate.SvgCoordinateStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SvgCoordinateStandaloneSetup extends SvgCoordinateStandaloneSetupGenerated {
  public static void doSetup() {
    new SvgCoordinateStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
