/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.path.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSvgPathScopeProvider extends DelegatingScopeProvider {
}
