/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.href.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSvgHrefScopeProvider extends DelegatingScopeProvider {
}
