/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.localiri


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SvgLocalIriStandaloneSetup extends SvgLocalIriStandaloneSetupGenerated {

	def static void doSetup() {
		new SvgLocalIriStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
