/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.points.validation;

import org.xtext.svg.points.validation.AbstractSvgPointsValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SvgPointsValidator extends AbstractSvgPointsValidator {
}
