/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.preserveaspectratio.formatting2;

import com.google.inject.Inject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.svg.preserveaspectratio.services.SvgPreserveAspectRatioGrammarAccess;

@SuppressWarnings("all")
public class SvgPreserveAspectRatioFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private SvgPreserveAspectRatioGrammarAccess _svgPreserveAspectRatioGrammarAccess;
  
  @Override
  public void format(final Object obj, final IFormattableDocument document) {
  }
}
