/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.length.formatting2;

import com.google.inject.Inject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.svg.length.services.SvgLengthGrammarAccess;

@SuppressWarnings("all")
public class SvgLengthFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private SvgLengthGrammarAccess _svgLengthGrammarAccess;
  
  @Override
  public void format(final Object obj, final IFormattableDocument document) {
  }
}
