/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.length


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SvgLengthStandaloneSetup extends SvgLengthStandaloneSetupGenerated {

	def static void doSetup() {
		new SvgLengthStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
