/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.paint.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.svg.paint.services.SvgPaintGrammarAccess;
import svg.IriPaint;
import svg.LocalIri;

@SuppressWarnings("all")
public class SvgPaintFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private SvgPaintGrammarAccess _svgPaintGrammarAccess;
  
  protected void _format(final IriPaint iriPaint, @Extension final IFormattableDocument document) {
    document.<LocalIri>format(iriPaint.getIri());
  }
  
  public void format(final Object iriPaint, final IFormattableDocument document) {
    if (iriPaint instanceof XtextResource) {
      _format((XtextResource)iriPaint, document);
      return;
    } else if (iriPaint instanceof IriPaint) {
      _format((IriPaint)iriPaint, document);
      return;
    } else if (iriPaint instanceof EObject) {
      _format((EObject)iriPaint, document);
      return;
    } else if (iriPaint == null) {
      _format((Void)null, document);
      return;
    } else if (iriPaint != null) {
      _format(iriPaint, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(iriPaint, document).toString());
    }
  }
}
