/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.paint.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSvgPaintScopeProvider extends DelegatingScopeProvider {
}
