/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.points;

import org.xtext.svg.points.AbstractSvgPointsRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SvgPointsRuntimeModule extends AbstractSvgPointsRuntimeModule {
}
