/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.points;

import org.xtext.svg.points.SvgPointsStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SvgPointsStandaloneSetup extends SvgPointsStandaloneSetupGenerated {
  public static void doSetup() {
    new SvgPointsStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
