/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.path;

import org.xtext.svg.path.AbstractSvgPathRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SvgPathRuntimeModule extends AbstractSvgPathRuntimeModule {
}
