/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.paint;

import org.xtext.svg.paint.SvgPaintStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SvgPaintStandaloneSetup extends SvgPaintStandaloneSetupGenerated {
  public static void doSetup() {
    new SvgPaintStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
