/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.paint;

import org.xtext.svg.paint.AbstractSvgPaintRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SvgPaintRuntimeModule extends AbstractSvgPaintRuntimeModule {
}
