/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.href.formatting2

import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.xtext.svg.href.services.SvgHrefGrammarAccess
import org.eclipse.xtext.formatting2.IFormattableDocument

class SvgHrefFormatter extends AbstractFormatter2 {
	
	@Inject extension SvgHrefGrammarAccess
	
	// TODO: implement for 
	override format(Object obj, IFormattableDocument document) {
		
	}
	
}
