/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.coordinate.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSvgCoordinateScopeProvider extends DelegatingScopeProvider {
}
