/*
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.length.formatting2

import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.xtext.svg.length.services.SvgLengthGrammarAccess
import org.eclipse.xtext.formatting2.IFormattableDocument

class SvgLengthFormatter extends AbstractFormatter2 {
	
	@Inject extension SvgLengthGrammarAccess
	
	// TODO: implement for 
	override format(Object obj, IFormattableDocument document) {
		
	}
	
}
