/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.lengths;

import org.xtext.svg.lengths.AbstractSvgLengthsRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SvgLengthsRuntimeModule extends AbstractSvgLengthsRuntimeModule {
}
