/**
 * generated by Xtext 2.12.0
 */
package org.xtext.svg.lengths;

import org.xtext.svg.lengths.SvgLengthsStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SvgLengthsStandaloneSetup extends SvgLengthsStandaloneSetupGenerated {
  public static void doSetup() {
    new SvgLengthsStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
